### ISSUE TITLE
Apollo ConfigService 启动报错

### ISSUE THREAD

**Issue by ikool-cn** [apolloconfig/apollo#4530] opened 2022-08-20 03:00 UTC
环境：JDK 1.8
MySQl：5.6.50
 数据库已导入，配置都已经修改了好了，启动不了
-------------------------------------------------------------------------------------
```
/usr/local/apollo/config/scripts/startup.sh
Sat Aug 20 10:37:46 CST 2022 ==== Starting ==== 
Started [29464]
Waiting for server startup.
pid - 29464 just quit unexpectedly, please check logs under /opt/logs/100003171 and /tmp for more information!
```

错误日志如下：
-------------------------------------------------------------------------------------
2022-08-20 10:37:47.151  INFO 29464 --- [main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class org.springframework.cloud.netflix.eureka.config.EurekaDiscoveryClientConfigServiceBootstrapConfiguration: java.lang.IllegalStateException: Could not obtain annotation attribute value for public abstract java.lang.Class[] org.springframework.boot.autoconfigure.condition.ConditionalOnClass.value()
2022-08-20 10:37:47.175  INFO 29464 --- [main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@66d78790: startup date [Sat Aug 20 10:37:47 CST 2022]; root of context hierarchy
2022-08-20 10:37:47.379 ERROR 29464 --- [main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Cannot load configuration class: org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.enhanceConfigurationClasses(ConfigurationClassPostProcessor.java:414)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanFactory(ConfigurationClassPostProcessor.java:254)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:282)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:126)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694)
...

**Comment by ikool-cn** [comment] 2022-08-20 03:08
提交重复了

**Comment by nobodyiam** [comment] 2022-08-20 11:43
Duplicate of #4529

**Closed by nobodyiam** 2022-08-20 11:43 UTC

**Comment by ikool-cn** [comment] 2022-08-21 03:08
折腾了一天终于解决了，最新版本的java18不行，要下老版本java8.。。。
