### ISSUE TITLE
Token: App('xxxxx') does not exist, please create it first

### ISSUE THREAD

**Issue by Marco-Zheng** [apolloconfig/apollo#3989] opened 2021-09-16 09:20 UTC
**Describe the bug**
I have create an app named `apisix-registry`, and appId also `apisix-registry`
![image](https://user-images.githubusercontent.com/52538259/133585787-b16d0a95-d858-4326-892d-390944b17f7a.png)
but when i create third-party applications and search `apisix-registry`, there had an error as below 
Token: App('apisix-registry') does not exist, please create it first
![image](https://user-images.githubusercontent.com/52538259/133586036-e3809f6c-03ff-4a05-8faf-002d290b9774.png)

**To Reproduce**
1. create an app
2. create third-party applications and search by appId

### Additional Details & Logs

- Version java-1.7.1

**Comment by nobodyiam** [comment] 2021-09-17 00:13
This is the designed behavior. The basic idea behind this is we have `some app` which wants to operate the configurations of `another app` in apollo.
Here `another app` is the `apisix-registry` you created in apollo. And `some app` happens to be the same app, but you still need to create it in the open api manage page to acquire the open api token.

**Comment by Marco-Zheng** [comment] 2021-09-17 02:24
@nobodyiam thanks for your reply, but i'm still confused, because when i use apollo-1.6.1, it can worked well
![image](https://user-images.githubusercontent.com/52538259/133713849-c3cb65c8-8894-453d-815a-7921de356cf6.png)
but when i use apollo-1.7.1, it was failed（apollo-1.7.1 and apollo-1.6.1 are using in different cluster, can't be changed）
so i guess if any adjuestment for apollo-1.7.1

 I want to use token to access the apisix-registry project, i now we create only one apisix-registry in apollo, how can i get the token, could you please give me any advice?

**Comment by Marco-Zheng** [comment] 2021-09-17 02:33
@nobodyiam Sorry, my operation was wrong, the problem has been solved, thanks a lot

**Comment by moonming** [comment] 2021-09-17 03:34
hello, I am from the Apache APISIX community.
Maybe we can integrate Apollo with Apache APISIX?

**Comment by kezhenxu94** [comment] 2021-09-17 03:42
Closing as the problem is resolved.

**Closed by kezhenxu94** 2021-09-17 03:42 UTC

**Comment by nobodyiam** [comment] 2021-09-18 00:19
@moonming Sounds a good idea! Apollo has [a set of http apis](https://www.apolloconfig.com/#/zh/usage/other-language-client-user-guide) to read/subscribe the configs and also has [a set of open apis](https://www.apolloconfig.com/#/zh/usage/apollo-open-api-platform) to operate the configs, you may take a look to see if works for apisix.
