### ISSUE TITLE
开启 oidc 后无法启动

### ISSUE THREAD

**Issue by liaolunhui** [apolloconfig/apollo#4252] opened 2022-03-06 10:49 UTC
- [x] 我已经检查过[discussions](https://github.com/ctripcorp/apollo/discussions)
- [x] 我已经搜索过[issues](https://github.com/ctripcorp/apollo/issues)
- [x] 我已经仔细检查过[FAQ](https://www.apolloconfig.com/#/zh/faq/common-issues-in-deployment-and-development-phase)

**描述bug**

使用 keycloak 15 做 oidc 认证

**复现**

通过如下步骤可以复现：

1. 使用 keycloak 15 做 oidc 认证

**期望**

正常启动

**截图**

![image](https://user-images.githubusercontent.com/13741751/156920003-98e6faa9-1178-4cca-a497-1b8cb3838971.png)

### 额外的细节和日志

- 版本：2.0
- 错误日志
- 	at org.springframework.security.oauth2.client.registration.ClientRegistrations.getBuilder(ClientRegistrations.java:221)
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.fromIssuerLocation(ClientRegistrations.java:145)
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getBuilderFromIssuerIfPossible(OAuth2ClientPropertiesRegistrationAdapter.java:83)
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistration(OAuth2ClientPropertiesRegistrationAdapter.java:59)
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.lambda$getClientRegistrations$0(OAuth2ClientPropertiesRegistrationAdapter.java:53)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientPropertiesRegistrationAdapter.getClientRegistrations(OAuth2ClientPropertiesRegistrationAdapter.java:52)
	at org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientRegistrationRepositoryConfiguration.clientRegistrationRepository(OAuth2ClientRegistrationRepositoryConfiguration.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 35 common frames omitted
Caused by: java.lang.RuntimeException: com.nimbusds.oauth2.sdk.ParseException: Unexpected type of JSON object member with key mtls_endpoint_aliases
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.parse(ClientRegistrations.java:232)
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.lambda$oidc$0(ClientRegistrations.java:157)
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.getBuilder(ClientRegistrations.java:209)
	... 47 common frames omitted
Caused by: com.nimbusds.oauth2.sdk.ParseException: Unexpected type of JSON object member with key mtls_endpoint_aliases
	at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getGeneric(JSONObjectUtils.java:161)
	at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getJSONObject(JSONObjectUtils.java:827)
	at com.nimbusds.oauth2.sdk.as.AuthorizationServerMetadata.parse(AuthorizationServerMetadata.java:2042)
	at com.nimbusds.openid.connect.sdk.op.OIDCProviderMetadata.parse(OIDCProviderMetadata.java:1362)
	at org.springframework.security.oauth2.client.registration.ClientRegistrations.parse(ClientRegistrations.java:229)
	... 49 common frames omitted
Caused by: com.nimbusds.oauth2.sdk.ParseException: Unexpected type: class java.util.LinkedHashMap
	at com.nimbusds.oauth2.sdk.util.JSONUtils.to(JSONUtils.java:100)
	at com.nimbusds.oauth2.sdk.util.JSONObjectUtils.getGeneric(JSONObjectUtils.java:159)
	... 53 common frames omitted
- 配置：
- 平台和操作系统

**Comment by mwxxhdb** [comment] 2022-03-15 06:06
用这个 repo 里的 docker-compose 文件可以复现 bug，不需要启动 keycloak。
配置上 oidc profile 后就会因为缺少 InMemoryClientRegistrationRepository 启动失败。

https://github.com/mwxxhdb/apollo-portal-oidc-issue

主要错误：Consider defining a bean of type 'org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository' in your configuration.

详细日志：
```
apollo-portal_1  | 2022-03-15 13:51:56.907  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authConfiguration.OidcWebSecurityConfigurerAdapter' defined in URL [jar:file:/apollo-portal/apollo-portal-1.9.2.jar!/BOOT-INF/classes!/com/ctrip/framework/apollo/portal/spi/configuration/AuthConfiguration$OidcWebSecurityConfigurerAdapter.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
...
apollo-portal_1  | 2022-03-15 13:51:57.076  WARN 1 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [Apollo-ConfigRefresher-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
apollo-portal_1  |  sun.misc.Unsafe.park(Native Method)
apollo-portal_1  |  java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
apollo-portal_1  |  java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
apollo-portal_1  |  java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
apollo-portal_1  |  java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
apollo-portal_1  |  java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
apollo-portal_1  |  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
apollo-portal_1  |  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
apollo-portal_1  |  java.lang.Thread.run(Thread.java:748)
apollo-portal_1  | 2022-03-15 13:51:57.077  WARN 1 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [Apollo-ConsumerAuditUtil-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
apollo-portal_1  |  sun.misc.Unsafe.park(Native Method)
apollo-portal_1  |  java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
apollo-portal_1  |  java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
apollo-portal_1  |  java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
apollo-portal_1  |  com.google.common.collect.Queues.drain(Queues.java:291)
apollo-portal_1  |  com.ctrip.framework.apollo.openapi.util.ConsumerAuditUtil.lambda$afterPropertiesSet$0(ConsumerAuditUtil.java:88)
apollo-portal_1  |  com.ctrip.framework.apollo.openapi.util.ConsumerAuditUtil$$Lambda$892/1977508673.run(Unknown Source)
apollo-portal_1  |  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
apollo-portal_1  |  java.util.concurrent.FutureTask.run(FutureTask.java:266)
apollo-portal_1  |  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
apollo-portal_1  |  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
apollo-portal_1  |  java.lang.Thread.run(Thread.java:748)
apollo-portal_1  | 2022-03-15 13:51:57.112  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :
apollo-portal_1  |
apollo-portal_1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
apollo-portal_1  | 2022-03-15 13:51:57.184 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :
apollo-portal_1  |
apollo-portal_1  | ***************************
apollo-portal_1  | APPLICATION FAILED TO START
apollo-portal_1  | ***************************
apollo-portal_1  |
apollo-portal_1  | Description:
apollo-portal_1  |
apollo-portal_1  | Parameter 0 of constructor in com.ctrip.framework.apollo.portal.spi.configuration.AuthConfiguration$OidcWebSecurityConfigurerAdapter required a bean of type 'org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository' that could not be found.
apollo-portal_1  |
apollo-portal_1  |
apollo-portal_1  | Action:
apollo-portal_1  |
apollo-portal_1  | Consider defining a bean of type 'org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository' in your configuration.
apollo-portal_1  |
```

**Comment by nobodyiam** [comment] 2022-03-16 00:51
@mwxxhdb will #4253 solve your problem too?

**Comment by mwxxhdb** [comment] 2022-03-16 01:15
> @mwxxhdb will #4253 solve your problem too?

tried that solution but the problem still exists.
I used the latest code from https://gitee.com/apolloconfig/apollo
Seems that repository is outdated, today evening I will use the code on github to test it again.

**Comment by mwxxhdb** [comment] 2022-03-16 04:26
> > @mwxxhdb will #4253 solve your problem too?
> 
> tried that solution but the problem still exists. I used the latest code from https://gitee.com/apolloconfig/apollo But seems that repository is outdated, today evening I will use the code on github to test it again.

Updates: The problem still exists after adding the dependency in #4253

**Comment by mwxxhdb** [comment] 2022-03-16 05:08
I may have found the cause of my problem, but I need more time to investigate, and I will inform you when I make progress.

**Comment by mwxxhdb** [comment] 2022-03-16 05:34
@nobodyiam the problem on my environment is because of I made an incorrect configuration file. I've updated my comment in this thread.

**Comment by nobodyiam** [comment] 2022-03-16 11:12
> 文档缩进问题
[开发文档 / Portal 实现用户登录功能 / 实现方式三： 接入OIDC / 1. 配置 application-oidc.yml / 1.2 扩展配置](https://www.apolloconfig.com/#/zh/development/portal-how-to-implement-user-login-function?id=_12-%e6%89%a9%e5%b1%95%e9%85%8d%e7%bd%ae) 这部分的配置没有正确缩进

This is strange... @Anilople have you met this issue before?
The [original markdown](https://github.com/apolloconfig/apollo/blob/master/docs/zh/development/portal-how-to-implement-user-login-function.md#12-%E6%89%A9%E5%B1%95%E9%85%8D%E7%BD%AE) seems correct:

![image](https://user-images.githubusercontent.com/837658/158577095-98af3760-e0ab-413c-9694-02001345f211.png)

But the rendered [html page](https://www.apolloconfig.com/#/zh/development/portal-how-to-implement-user-login-function?id=_12-%e6%89%a9%e5%b1%95%e9%85%8d%e7%bd%ae) is wrong:

![image](https://user-images.githubusercontent.com/837658/158577275-2c4612a7-5aa6-4af8-b72a-bd43c1aedb39.png)

> 没有理解文档中的配置，所以把 provider-name 当成了和 issuer-uri 同级的一个属性

Do you have any suggestion to improve this guide?

**Comment by mwxxhdb** [comment] 2022-03-17 08:02
> > 没有理解文档中的配置，所以把 provider-name 当成了和 issuer-uri 同级的一个属性
> 
> @mwxxhdb Do you have any suggestions to improve this guide?

Maybe it would be better to replace the `provider-name` with `changeme`?
Or use properties format instead of yaml

**Comment by nobodyiam** [comment] 2022-03-18 01:11
> Maybe it would be better to replace the provider-name with changeme?

This sounds like a good idea, would you please help to submit a fix for this?

> Or use properties format instead of yaml

This might be a workaround, but that would make the configuration cumbersome, I think we could first investigate why the HTML page renders the wrong syntax.

**Closed** 2022-03-18 05:11 UTC
